version: "3.9"

services:
  backend:
    image: mugheesulhassan/backend
    container_name: backend-jenkins
    ports:
      - "5000:4000"  # changed to avoid conflict
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"

  user-frontend:
    image: mugheesulhassan/user-frontend
    container_name: user-frontend-jenkins
    ports:
      - "3001:3000"
    volumes:
      - ./user-frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  admin-frontend:
    image: mugheesulhassan/admin-frontend
    container_name: admin-frontend-jenkins
    ports:
      - "3002:3000"
    volumes:
      - ./admin-frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_jenkins
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - user-frontend
      - admin-frontend

